#!/usr/bin/env python3
from __future__ import annotations

import argparse
from typing import Optional
from typing import Sequence


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('name')
    args = parser.parse_args(argv)

    print(f'Hello {args.name}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
