#!/usr/bin/env python3
import argparse
from typing import Optional
from typing import Sequence


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('name')
    args = parser.parse_args(argv)

    print(f'Hello {args.name}')
    return 0


if __name__ == '__main__':
    exit(main())
